version: 2
builds: []

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: 'dist/fuzzer-ubuntu-latest/fuzzer'
        goos: linux
      - src: 'dist/fuzzer-macos-latest/fuzzer' # This covers macOS
        goos: darwin
      - src: 'dist/fuzzer-windows-latest/fuzzer.exe'
        goos: windows
