name: release
on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true # This makes builds much faster by reusing dependencies

      - name: Install Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Build
        shell: bash
        run: |
          mkdir -p bin
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            go build -ldflags="-s -w" -o bin/fuzzer.exe .
          else
            go build -ldflags="-s -w" -o bin/fuzzer .
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuzzer-${{ matrix.os }}
          path: bin/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: List what is in dist
        run: ls -R dist/
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/fuzzer-windows-latest/fuzzer.exe
            dist/fuzzer-ubuntu-latest/fuzzer
            dist/fuzzer-macos-latest/fuzzer
